# Generated by Django 3.0 on 2020-06-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiitNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('read_count', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aiit_news',
                'managed': False,
            },
        ),
    ]
